name: Node.js CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      env:
        CI: true
        MONGO_URI: mongodb://localhost:27017/jobtracing_test
        JWT_SECRET: test_secret
    
    - name: Build client
      run: |
        cd client
        npm ci
        npm run build
      env:
        CI: true
        
    - name: Setup MongoDB Atlas CLI
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        curl -sSfL https://raw.githubusercontent.com/mongodb/mongocli/main/scripts/install.sh | sh
        export PATH=$PATH:$HOME/.mongocli/bin
        mongocli config init
      env:
        MCLI_PUBLIC_API_KEY: ${{ secrets.ATLAS_API_PUBLIC_KEY }}
        MCLI_PRIVATE_API_KEY: ${{ secrets.ATLAS_API_PRIVATE_KEY }}
        
    - name: Deploy to MongoDB Atlas App Services
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        # Package and deploy the Atlas App Services app
        cd app_config
        zip -r ../app_config.zip .
        mongocli appservices app deploy ${{ secrets.REALM_APP_ID }} --file=../app_config.zip --follow
      env:
        MCLI_PUBLIC_API_KEY: ${{ secrets.ATLAS_API_PUBLIC_KEY }}
        MCLI_PRIVATE_API_KEY: ${{ secrets.ATLAS_API_PRIVATE_KEY }}
    
    - name: Deploy to hosting service
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Deploying to production server..."
        # Add deployment commands here based on your hosting provider
        # For example: netlify deploy, vercel deploy, etc.
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        REALM_APP_ID: ${{ secrets.REALM_APP_ID }} 