name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup MongoDB Collections
        run: |
          mkdir -p .github/scripts
          npm install mongodb
          node .github/scripts/setup-mongodb.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Install Dependencies
        run: |
          cd client
          npm install --legacy-peer-deps

      - name: Build
        run: |
          cd client
          npm run build
        env:
          CI: false
          TSC_COMPILE_ON_ERROR: true
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_MONGODB_APP_ID: ${{ secrets.MONGODB_APP_ID }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/build
          branch: gh-pages
          clean: true 